<a href="https://colab.research.google.com/github/emrllh/My_works/blob/main/transformer_anatomy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!git clone https://github.com/nlp-with-transformers/notebooks.git
#%cd notebooks
#from install import *
#install_requirements()

Cloning into 'notebooks'...
remote: Enumerating objects: 530, done.
remote: Counting objects: 100% (210/210), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 530 (delta 184), reused 162 (delta 162), pack-reused 320 (from 2)
Receiving objects: 100% (530/530), 28.52 MiB | 20.17 MiB/s, done.
Resolving deltas: 100% (253/253), done.
/content/notebooks/notebooks/notebooks
⏳ Installing base requirements ...
✅ Base requirements installed!
⏳ Installing Git LFS ...
✅ Git LFS installed!


In [ ]:
#hide
from utils import *
setup_chapter()

ModuleNotFoundError: No module named 'utils'

In [ ]:
%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

<IPython.core.display.Javascript object>

In [ ]:
!pip install bertviz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.6/157.6 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 108.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 79.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 54.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 42.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 kB 13.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
from transformers import AutoTokenizer
from bertviz.transformers_neuron_view import BertModel
from bertviz.neuron_view import show

In [ ]:
model_ckpt = "bert-base-uncased"

In [ ]:
from transformers import BertModel
model_ckpt = "bert-base-uncased"
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
model = BertModel.from_pretrained(model_ckpt)
text = "time flies like an arrow"
show(model, "bert", tokenizer, text, display_mode="light", layer=0, head=8)


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

NameError: name 'show' is not defined

####  Demystifying Queries, Keys, and Values

In [ ]:
inputs = tokenizer(text, return_tensors="tf", add_special_tokens=False)
inputs.input_ids

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 2051, 10029,  2066,  2019,  8612]], dtype=int32)>

In [ ]:
#!pip install -q diffusers transformers accelerate peft

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 6.7 MB/s eta 0:00:00


In [ ]:
model_ckpt = "bert-base-cased"

In [ ]:
import tensorflow as tf
from transformers import AutoConfig

config = AutoConfig.from_pretrained(model_ckpt)
token_emb = tf.keras.layers.Embedding(config.vocab_size, config.hidden_size)
token_emb #Embedding(30522, 768)

<Embedding name=embedding_1, built=False>

In [ ]:
inputs_embeds = token_emb(inputs.input_ids)
inputs_embeds.shape

TensorShape([1, 5, 768])

In [ ]:
from math import sqrt

query = key = value = inputs_embeds
dim_k = key.shape[-1]
print(dim_k)
scores = tf.matmul(query, key, transpose_b=True) / sqrt(dim_k)
scores.shape

768


TensorShape([1, 5, 5])

`key.shape[-1]` is used to get the last dimension of the key tensor, which represents the dimensionality of the embedding vectors (also known as the hidden size). In other words, it's the number of features used to represent each word.

In [ ]:
weights = tf.nn.softmax(scores, axis=-1)
print(weights)
weights_sum =tf.reduce_sum(weights, axis=-1)
print(weights_sum)

tf.Tensor(
[[[0.20389952 0.19890915 0.1990825  0.19897829 0.19913054]
  [0.1989092  0.20383552 0.1990994  0.19899239 0.19916348]
  [0.19902149 0.19903834 0.20393316 0.19894795 0.19905901]
  [0.19911234 0.1991264  0.19914299 0.20365241 0.19896583]
  [0.19919021 0.19922313 0.19917971 0.19889148 0.20351543]]], shape=(1, 5, 5), dtype=float32)
tf.Tensor([[1.         1.         1.         0.99999994 0.99999994]], shape=(1, 5), dtype=float32)


In [ ]:
attn_outputs = tf.matmul(weights, value)
attn_outputs.shape

TensorShape([1, 5, 768])

The code you provided calculates the attention weights using the softmax function and then sums these weights along the last axis (axis=-1).

Reasoning for using axis=-1

Understanding the Shape: The weights tensor likely has a shape like (batch_size, sequence_length, sequence_length). Each element weights[i, j, k] represents the attention weight between the i-th element in the batch, the j-th word in the query sequence, and the k-th word in the key sequence.

Summing across the Key Dimension: We want to sum the attention weights across all possible key words for each query word. This is done to normalize the attention weights so that they represent a probability distribution over the key words. Since the key words are represented by the last dimension of the weights tensor, we use axis=-1 to sum across that dimension.

In simpler terms:

Imagine you have a table where rows represent query words, columns represent key words, and the values in the cells are attention weights. Using axis=-1 is like summing up the values in each row of the table. This gives you the total attention weight for each query word, considering all the key words.

Why it's Important:

Normalization: The sum of attention weights along axis=-1 should ideally be close to 1 for each query word. This ensures that the weights represent a probability distribution and that the attention mechanism is properly normalized.
Focus: This summation helps the model focus on the most relevant key words for each query word by assigning higher attention weights to them. The weights after summation represent the relative importance of each key word to the query word

In [ ]:
#Put everyting in a function

def scaled_dot_product_attention(query, key, value):
  dim_k = query.shape[-1]
  scores = tf.matmul(query, key, transpose_b=True)/sqrt(dim_k)
  weights = tf.nn.softmax(scores, axis=-1)
  return tf.matmul(weights, value)

#### *Multi-headed attention*

In [ ]:
class AttentionHead(tf.keras.layers.Layer):
  def __init__(self,embed_dim, head_dim):
    super().__init__()

    self.q = tf.keras.layers.Dense(head_dim,activation='relu')
    self.k = tf.keras.layers.Dense(head_dim,activation='relu')
    self.v = tf.keras.layers.Dense(head_dim,activation='relu')

  def call(self, hidden_state):
    attn_outputs = scaled_dot_product_attention(
        self.q(hidden_state), self.k(hidden_state), self.v(hidden_state))
    return attn_outputs

In [ ]:
"""import keras

class AttentionHead(keras.layers.Layer):
  def __init__(self, embed_dim, head_dim):
    super().__init__()
    self.q = keras.layers.Dense(embed_dim, head_dim,activation='relu')
    self.k = keras.layers.Dense(embed_dim, head_dim,activation='relu')
    self.v = keras.layers.Dense(embed_dim, head_dim,activation='relu')

  def call(self, hidden_state):
    attn_outputs = scaled_dot_product_attention(
        self.q(hidden_state), self.k(hidden_state), self.v(hidden_state))

    return attn_outputs"""

In [ ]:
attn_heads = AttentionHead(config.hidden_size ,config.hidden_size // config.num_attention_heads)
attn_outputs = attn_heads(inputs_embeds)
attn_outputs.shape

TensorShape([1, 5, 64])

In [ ]:
class MultiHeadAttention(keras.layers.Layer):
  def __init__(self, config):
    super().__init__()
    embed_dim = config.hidden_size
    num_heads = config.num_attention_heads
    head_dim = embed_dim // num_heads
    self.heads =keras.layers.Dense(
        [AttentionHead(embed_dim,head_dim) for _ in range(num_heads)])

    self.output_linear = keras.layers.Dense(embed_dim,activation='relu')


  def call(self, hidden_state):
    x = keras.layers.concatenate([h(hidden_state) for h in self.heads])
    x = self.output_linear(x)
    return x

In [ ]:
multihead_attn = MultiHeadAttention(config)
attn_output = multihead_attn(inputs_embeds)
attn_output.shape

TypeError: Exception encountered when calling MultiHeadAttention.call().

'Dense' object is not iterable

Arguments received by MultiHeadAttention.call():
  • hidden_state=tf.Tensor(shape=(1, 5, 768), dtype=float32)

In [ ]:
from bertviz import head_view
from transformers import AutoModel

model = AutoModel.from_pretrained(model_ckpt, output_attentions=True)

sentence_a = "time flies like an arrow"
sentence_b = "fruit flies like a banana"

viz_inputs = tokenizer(sentence_a, sentence_b, return_tensors='pt')
attention = model(**viz_inputs).attentions
sentence_b_start = (viz_inputs.token_type_ids == 0).sum(dim=1)
tokens = tokenizer.convert_ids_to_tokens(viz_inputs.input_ids[0])

head_view(attention, tokens, sentence_b_start, heads=[8])

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

BertSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.


<IPython.core.display.Javascript object>

### The Feed-Forward Layer

In [ ]:
import keras
class FeedForward(keras.layers.Layer):
  def __init__(self, config):
    super().__init__()
    self.linear_1 = keras.layers.Dense(config.hidden_size, config.intermediate_size)
    self.linear_2 = keras.layers.Dense(config.intermediate_size, config.hidden_size)
    self.gelu = keras.layers.Activation("gelu")
    self.dropout = keras.layers.Dropout(config.hidden_dropout_prob)

    def call(self, x):
      x = self.linear_1(x)
      x = self.gelu(x)
      x = self.linear_2(x)
      x = self.dropout(x)
      return x

In [ ]:
feed_forward = FeedForward(config)
ff_outputs = feed_forward(attn_outputs)
ff_outputs.shape

ValueError: Could not interpret activation function identifier: 3072

### Adding Layer Normalization

In [ ]:
class TransformerEncoderLayer(keras.layers.Layer):
  def __init__(self, config):
    super().__init__()

    self.layer_norm_1 = keras.layers.LayerNormalization(config.hidden_size)
    self.layer_norm_2 = keras.layers.LayerNormalization(config.hidden_size)
    self.attention = MultiHeadAttention(config)
    self.feed_forward = FeedForward(config)

  def call(self, x):
    # Apply layer normalization and then copy input into query, key, value
    hidden_state = self.layer_norm_1(x)
    # Apply attention with a skip connection
    x = x + self.attention(hidden_state)
    # Apply feed-forward layer with a skip connection
    x = x + self.feed_forward(self.layer_norm_2(x))

    return x



What is a Skip Connection?

In deep learning, a skip connection (or residual connection) is a technique where the output of a layer is added to the input of a later layer. Instead of just passing the output of one layer directly to the next, we create a "shortcut" where the original input is also combined with the output.

How it Works in Your Code:

x: Represents the input to the current layer (likely the output of a previous layer).
self.feed_forward(self.layer_norm_2(x)): This part applies a feed-forward network and layer normalization to the input x. Let's call the result of this operation F(x).
x + F(x): This is where the skip connection happens. The original input x is added to the transformed output F(x). The result is then assigned back to x, becoming the output of this layer.
Why Skip Connections Are Used:

Improved Gradient Flow: Skip connections help gradients flow more easily through deep networks during training. This is especially important in very deep architectures, where gradients can vanish or explode, making it difficult to train effectively.
Faster Convergence: By allowing gradients to flow more freely, skip connections can help the network converge to a good solution faster.
Mitigation of Vanishing Gradients: In deep networks, gradients can become very small as they are backpropagated through many layers. Skip connections provide an alternate path for gradients to flow, mitigating this problem.
Enables Deeper Networks: Skip connections have been a key factor in enabling the training of very deep neural networks.
In the Context of Transformers:

Skip connections are a fundamental component of Transformer architectures. They are used in both the encoder and decoder parts to help stabilize training and improve performance. They are crucial for the success of Transformers in various natural language processing tasks.

In [ ]:
encoder_layer = TransformerEncoderLayer(config)
inputs_embeds.shape, encoder_layer(inputs_embeds).shape

ValueError: Could not interpret activation function identifier: 768

### Positional Embeddings

In [ ]:
class Embeddings(keras.layers.Layer):
  def __init__(self, config):
    super().__init__()
    self.token_embeddins = keras.layers.layer.Embedding(config.vocab_size,
                                                        config.hidden_size)
    self.position_embeddings = keras.layers.layer.Embedding(config.max_position_embeddings,
                                                            config.hidden_size)
    self.layer_norm = keras.layers.LayerNormalization(config.hidden_size, eps=1e-12)
    self.dropout = keras.layers.Dropout()

  def call(self, input_ids):
    # Create position IDs for input sequence
    seq_length = input_ids.shape[1]
    position_ids = tf.range(seq_length)

    # Create token and position embeddings
    token_embeddings = self.token_embeddings(input_ids)
    position_embeddings = self.position_embeddings(position_ids)

    # Combine token and position embeddings
    embeddings = token_embeddings + position_embeddings
    embeddings = self.layer_norm(embeddings)
    embeddings = self.dropout(embeddings)
    return embeddings


In [ ]:
embedding_layer = Embeddings(config)
embedding_layer(inputs.input_ids).shape

AttributeError: module 'keras.api.layers' has no attribute 'layer'

In [ ]:
# Put them all together to create Transformer Encoder combining embeddings with the encoder layers
class TransformerEncoder(keras.layers.layer):
  def __init__(self, config):
    super.__init__()
    self.embeddings = Embeddings(config)
    self.layers = [TransformerEncoderLayer(config) for _ in range(config.num_hidden_layers)]

  def call(self, x):
    x = self.embeddings(x)
    for layer in self.layers:
      x = layer(x)
    return x

#### Adding a Classification Head

In [ ]:
class TransformerForSequenceClassification(keras.layers.layer):
  def __init__(self,config):
    super().__init__()
    self.encoder = TransformerEncoder(config)
    self.dropout = keras.layers.layer(config.hidden_size)
    self.classifier = keras.layers.layer(config.num_labels)

  def call(self, x):
    x = self.encoder(x)[:, 0, :] # select hidden state of [CLS] token
    x = self.dropout(x)
    x = self.classifier(x)
    return x

In [ ]:
config.num_labels = 3
encoder_classifier = TransformerForSequenceClassification(config)
encoder_classifier(inputs.input_ids).shape